/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feederplace;

import com.sun.xml.internal.ws.util.StringUtils;
import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class ReadTxt extends javax.swing.JPanel {

    /**
     * Creates new form ReadTxt
     */
    public ReadTxt() {
        initComponents();
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane47 = new javax.swing.JScrollPane();
        jTable45 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        F1to5T482 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        F6to10T482 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        F11to15T482 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        F1to5T411 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        OveflowFeederName = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        F51T411 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        F6to10T411 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        F11to15T411 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        F16to20T482 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        F21to25T482 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        F16to20T411 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        F21to25T411 = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        F26to30T482 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        F26to30T411 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        F31to35T482 = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        F31to35T411 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        F53T411 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        F52T411 = new javax.swing.JTable();
        jScrollPane19 = new javax.swing.JScrollPane();
        F54T411 = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        F36to40T482 = new javax.swing.JTable();
        jScrollPane21 = new javax.swing.JScrollPane();
        F36to40T411 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane22 = new javax.swing.JScrollPane();
        F55T411 = new javax.swing.JTable();
        jScrollPane23 = new javax.swing.JScrollPane();
        F56T411 = new javax.swing.JTable();
        jScrollPane24 = new javax.swing.JScrollPane();
        F57T411 = new javax.swing.JTable();
        jScrollPane25 = new javax.swing.JScrollPane();
        F58T411 = new javax.swing.JTable();
        jScrollPane26 = new javax.swing.JScrollPane();
        F59T411 = new javax.swing.JTable();
        jScrollPane27 = new javax.swing.JScrollPane();
        F60T411 = new javax.swing.JTable();
        jScrollPane28 = new javax.swing.JScrollPane();
        R51T411 = new javax.swing.JTable();
        jScrollPane29 = new javax.swing.JScrollPane();
        R52T411 = new javax.swing.JTable();
        jScrollPane30 = new javax.swing.JScrollPane();
        R53T411 = new javax.swing.JTable();
        jScrollPane31 = new javax.swing.JScrollPane();
        R54T411 = new javax.swing.JTable();
        jScrollPane32 = new javax.swing.JScrollPane();
        R55T411 = new javax.swing.JTable();
        jScrollPane33 = new javax.swing.JScrollPane();
        R56T411 = new javax.swing.JTable();
        jScrollPane34 = new javax.swing.JScrollPane();
        F41to45T482 = new javax.swing.JTable();
        jScrollPane35 = new javax.swing.JScrollPane();
        F46to50T482 = new javax.swing.JTable();
        jScrollPane36 = new javax.swing.JScrollPane();
        F41to45T411 = new javax.swing.JTable();
        jScrollPane37 = new javax.swing.JScrollPane();
        F46to50T411 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane38 = new javax.swing.JScrollPane();
        R1to5T482 = new javax.swing.JTable();
        jScrollPane39 = new javax.swing.JScrollPane();
        R6to10T482 = new javax.swing.JTable();
        jScrollPane40 = new javax.swing.JScrollPane();
        R11to15T482 = new javax.swing.JTable();
        jScrollPane41 = new javax.swing.JScrollPane();
        R16to20T482 = new javax.swing.JTable();
        jScrollPane42 = new javax.swing.JScrollPane();
        R21to25T482 = new javax.swing.JTable();
        jScrollPane43 = new javax.swing.JScrollPane();
        R26to30T482 = new javax.swing.JTable();
        jScrollPane44 = new javax.swing.JScrollPane();
        R31to35T482 = new javax.swing.JTable();
        jScrollPane45 = new javax.swing.JScrollPane();
        R36to40T482 = new javax.swing.JTable();
        jScrollPane46 = new javax.swing.JScrollPane();
        F51to55T482 = new javax.swing.JTable();
        jScrollPane48 = new javax.swing.JScrollPane();
        F56to60T482 = new javax.swing.JTable();
        jScrollPane49 = new javax.swing.JScrollPane();
        R1to5T411 = new javax.swing.JTable();
        jScrollPane50 = new javax.swing.JScrollPane();
        R6to10T411 = new javax.swing.JTable();
        jScrollPane51 = new javax.swing.JScrollPane();
        R11to15T411 = new javax.swing.JTable();
        jScrollPane52 = new javax.swing.JScrollPane();
        R16to20T411 = new javax.swing.JTable();
        jScrollPane53 = new javax.swing.JScrollPane();
        R21to25T411 = new javax.swing.JTable();
        jScrollPane54 = new javax.swing.JScrollPane();
        R26to30T411 = new javax.swing.JTable();
        jScrollPane55 = new javax.swing.JScrollPane();
        R31to35T411 = new javax.swing.JTable();
        jScrollPane56 = new javax.swing.JScrollPane();
        R36to40T411 = new javax.swing.JTable();
        jScrollPane57 = new javax.swing.JScrollPane();
        R41to45T411 = new javax.swing.JTable();
        jScrollPane58 = new javax.swing.JScrollPane();
        R46to50T411 = new javax.swing.JTable();
        jScrollPane59 = new javax.swing.JScrollPane();
        R57T411 = new javax.swing.JTable();
        jScrollPane60 = new javax.swing.JScrollPane();
        R58T411 = new javax.swing.JTable();
        jScrollPane61 = new javax.swing.JScrollPane();
        R59T411 = new javax.swing.JTable();
        jScrollPane62 = new javax.swing.JScrollPane();
        R60T411 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane63 = new javax.swing.JScrollPane();
        OverflowProjectName = new javax.swing.JTable();
        jScrollPane64 = new javax.swing.JScrollPane();
        OverflowPosition = new javax.swing.JTable();

        jTable45.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F46", "F47", "F48", "F49", "F50"
            }
        ));
        jScrollPane47.setViewportView(jTable45);

        jButton1.setText("Add Project1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("Add Project2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.setText("Add Project3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        F1to5T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F1", "F2", "F3", "F4", "F5"
            }
        ));
        F1to5T482.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(F1to5T482);

        jLabel1.setText("Trolley1/ 482 Front");

        jLabel2.setText("Trolley2/ 411 Front");

        jLabel3.setText("Trolley 3 (1-10/F51-60)");

        F6to10T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F6", "F7", "F8", "F9", "F10"
            }
        ));
        jScrollPane2.setViewportView(F6to10T482);

        jLabel4.setText("Overflow");

        F11to15T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F11", "F12", "F13", "F14", "F15"
            }
        ));
        jScrollPane3.setViewportView(F11to15T482);

        F1to5T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F1", "F2", "F3", "F4", "F5"
            }
        ));
        jScrollPane4.setViewportView(F1to5T411);

        OveflowFeederName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Feeder Name"
            }
        ));
        jScrollPane5.setViewportView(OveflowFeederName);

        F51T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "1 (F51)"
            }
        ));
        jScrollPane6.setViewportView(F51T411);

        F6to10T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F6", "F7", "F8", "F9", "F10"
            }
        ));
        jScrollPane7.setViewportView(F6to10T411);

        F11to15T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F11", "F12", "F13", "F14", "F15"
            }
        ));
        jScrollPane8.setViewportView(F11to15T411);

        F16to20T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F16", "F17", "F18", "F19", "F20"
            }
        ));
        jScrollPane9.setViewportView(F16to20T482);

        F21to25T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F21", "F22", "F23", "F24", "F25"
            }
        ));
        jScrollPane10.setViewportView(F21to25T482);

        F16to20T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F16", "F17", "F18", "F19", "F20"
            }
        ));
        jScrollPane11.setViewportView(F16to20T411);

        F21to25T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F21", "F22", "F23", "F24", "F25"
            }
        ));
        jScrollPane12.setViewportView(F21to25T411);

        F26to30T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F26", "F27", "F28", "F29", "F30"
            }
        ));
        jScrollPane13.setViewportView(F26to30T482);

        F26to30T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F26", "F27", "F28", "F29", "F30"
            }
        ));
        jScrollPane14.setViewportView(F26to30T411);

        F31to35T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F31", "F32", "F33", "F34", "F35"
            }
        ));
        jScrollPane15.setViewportView(F31to35T482);

        F31to35T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F31", "F32", "F33", "F34", "F35"
            }
        ));
        jScrollPane16.setViewportView(F31to35T411);

        F53T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "3 (F53)"
            }
        ));
        jScrollPane17.setViewportView(F53T411);

        F52T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "2 (F52)"
            }
        ));
        jScrollPane18.setViewportView(F52T411);

        F54T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "4 (F54)"
            }
        ));
        jScrollPane19.setViewportView(F54T411);

        F36to40T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F36", "F37", "F38", "F39", "F40"
            }
        ));
        jScrollPane20.setViewportView(F36to40T482);

        F36to40T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F36", "F37", "F38", "F39", "F40"
            }
        ));
        jScrollPane21.setViewportView(F36to40T411);

        jButton4.setText("Common Parts");

        F55T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "5 (F55)"
            }
        ));
        jScrollPane22.setViewportView(F55T411);

        F56T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "6 (F56)"
            }
        ));
        jScrollPane23.setViewportView(F56T411);

        F57T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "7 (F57)"
            }
        ));
        jScrollPane24.setViewportView(F57T411);

        F58T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "8 (F58)"
            }
        ));
        jScrollPane25.setViewportView(F58T411);

        F59T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "9 (F59)"
            }
        ));
        jScrollPane26.setViewportView(F59T411);

        F60T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "10 (F60)"
            }
        ));
        jScrollPane27.setViewportView(F60T411);

        R51T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "1 (R51)"
            }
        ));
        jScrollPane28.setViewportView(R51T411);

        R52T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "2 (R52)"
            }
        ));
        jScrollPane29.setViewportView(R52T411);

        R53T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "3 (R53)"
            }
        ));
        jScrollPane30.setViewportView(R53T411);

        R54T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "4 (R54)"
            }
        ));
        jScrollPane31.setViewportView(R54T411);

        R55T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "5 (R55)"
            }
        ));
        jScrollPane32.setViewportView(R55T411);

        R56T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "6 (R56)"
            }
        ));
        jScrollPane33.setViewportView(R56T411);

        F41to45T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F41", "F42", "F43", "F44", "F45"
            }
        ));
        jScrollPane34.setViewportView(F41to45T482);

        F46to50T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F46", "F47", "F48", "F49", "F50"
            }
        ));
        jScrollPane35.setViewportView(F46to50T482);

        F41to45T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F41", "F42", "F43", "F44", "F45"
            }
        ));
        jScrollPane36.setViewportView(F41to45T411);

        F46to50T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "F46", "F47", "F48", "F49", "F50"
            }
        ));
        jScrollPane37.setViewportView(F46to50T411);

        jLabel5.setText("Trolley1/ 482 Rear");

        jLabel6.setText("Trolley2/ 411 Rear");

        jLabel7.setText("Trolley 3 (1-10/R51-60)");

        R1to5T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R1", "R2", "R3", "R4", "R5"
            }
        ));
        R1to5T482.getTableHeader().setReorderingAllowed(false);
        jScrollPane38.setViewportView(R1to5T482);

        R6to10T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R6", "R7", "R8", "R9", "R10"
            }
        ));
        jScrollPane39.setViewportView(R6to10T482);

        R11to15T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R11", "R12", "R13", "R14", "R15"
            }
        ));
        jScrollPane40.setViewportView(R11to15T482);

        R16to20T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R16", "R17", "R18", "R19", "R20"
            }
        ));
        jScrollPane41.setViewportView(R16to20T482);

        R21to25T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R21", "R22", "R23", "R24", "R25"
            }
        ));
        jScrollPane42.setViewportView(R21to25T482);

        R26to30T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R26", "R27", "R28", "R29", "R30"
            }
        ));
        jScrollPane43.setViewportView(R26to30T482);

        R31to35T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R31", "R32", "R33", "R34", "R35"
            }
        ));
        jScrollPane44.setViewportView(R31to35T482);

        R36to40T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R36", "R37", "R38", "R39", "R40"
            }
        ));
        jScrollPane45.setViewportView(R36to40T482);

        F51to55T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R41 (F51)", "R42 (F52)", "R43 (F53)", "R44 (F54)", "R45 (F55)"
            }
        ));
        jScrollPane46.setViewportView(F51to55T482);

        F56to60T482.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R46 (F56)", "R47 (F57)", "R48 (F58)", "R49 (F59)", "R50 (F60)"
            }
        ));
        jScrollPane48.setViewportView(F56to60T482);

        R1to5T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R1", "R2", "R3", "R4", "R5"
            }
        ));
        R1to5T411.getTableHeader().setReorderingAllowed(false);
        jScrollPane49.setViewportView(R1to5T411);

        R6to10T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R6", "R7", "R8", "R9", "R10"
            }
        ));
        jScrollPane50.setViewportView(R6to10T411);

        R11to15T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R11", "R12", "R13", "R14", "R15"
            }
        ));
        jScrollPane51.setViewportView(R11to15T411);

        R16to20T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R16", "R17", "R18", "R19", "R20"
            }
        ));
        jScrollPane52.setViewportView(R16to20T411);

        R21to25T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R21", "R22", "R23", "R24", "R25"
            }
        ));
        jScrollPane53.setViewportView(R21to25T411);

        R26to30T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R26", "R27", "R28", "R29", "R30"
            }
        ));
        jScrollPane54.setViewportView(R26to30T411);

        R31to35T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R31", "R32", "R33", "R34", "R35"
            }
        ));
        jScrollPane55.setViewportView(R31to35T411);

        R36to40T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R36", "R37", "R38", "R39", "R40"
            }
        ));
        jScrollPane56.setViewportView(R36to40T411);

        R41to45T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R41", "R42", "R43", "R44", "R45"
            }
        ));
        jScrollPane57.setViewportView(R41to45T411);

        R46to50T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "R46", "R47", "R48", "R49", "R50"
            }
        ));
        jScrollPane58.setViewportView(R46to50T411);

        R57T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "7 (R57)"
            }
        ));
        jScrollPane59.setViewportView(R57T411);

        R58T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "8 (R58)"
            }
        ));
        jScrollPane60.setViewportView(R58T411);

        R59T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "9 (R59)"
            }
        ));
        jScrollPane61.setViewportView(R59T411);

        R60T411.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "10 (R60)"
            }
        ));
        jScrollPane62.setViewportView(R60T411);

        jLabel8.setText("Trolley1/ 482 Front 50-60");

        OverflowProjectName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Project Name"
            }
        ));
        jScrollPane63.setViewportView(OverflowProjectName);

        OverflowPosition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane64.setViewportView(OverflowPosition);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane38, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane39)
                                    .addComponent(jScrollPane40, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane41)
                                    .addComponent(jScrollPane42)
                                    .addComponent(jScrollPane43)
                                    .addComponent(jScrollPane44)
                                    .addComponent(jScrollPane45)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3)
                                                .addComponent(jScrollPane9)
                                                .addComponent(jScrollPane10)
                                                .addComponent(jScrollPane13)
                                                .addComponent(jScrollPane15))
                                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 4, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                        .addComponent(jScrollPane7)
                                        .addComponent(jScrollPane8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                                        .addComponent(jScrollPane14))
                                    .addGap(6, 6, 6)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(111, 111, 111)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane54)
                                    .addComponent(jScrollPane55)
                                    .addComponent(jScrollPane50)
                                    .addComponent(jScrollPane49)
                                    .addComponent(jScrollPane51, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane52, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane53, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(495, 495, 495)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane37, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                                    .addComponent(jScrollPane36)
                                    .addComponent(jScrollPane21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane56, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane57, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane58))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane61, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane62, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)))
                .addComponent(jScrollPane64, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addGap(393, 393, 393)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane63, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(5, 5, 5)
                                                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane54, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane56, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane61, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane62, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane58, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane63, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane64, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int returnValue = chooser.showOpenDialog(this);
        File selectedFile = null;
        JOptionPane optionPane = new JOptionPane();
        JOptionPane exist = new JOptionPane();
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = chooser.getSelectedFile();
        } else {

        }
        try {
            String filename = selectedFile.getName();
            String extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
            String txt = "txt";

            if ((extension.compareTo(txt)) == 0) {
                jButton1.setEnabled(false);
                jButton2.setEnabled(true);
            } else {

                while ((extension.compareTo(txt)) != 0) {
                    optionPane.showMessageDialog(null, "Choose a txt file!");
                    chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    returnValue = chooser.showOpenDialog(this);
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        selectedFile = chooser.getSelectedFile();
                    } else {

                    }
                    filename = selectedFile.getName();
                    extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
                    //AddButton1.setEnabled(true);!!!!!!!!!!!!!!!!!!!!!!!!
                }
                jButton1.setEnabled(false);
                jButton2.setEnabled(true);
            }
            project1 = selectedFile.getAbsolutePath();
            readProject1Txt();

        } catch (NullPointerException e) {

        } catch (IOException ex) {
            Logger.getLogger(ReadTxt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int returnValue = chooser.showOpenDialog(this);
        File selectedFile = null;
        JOptionPane optionPane = new JOptionPane();
        JOptionPane exist = new JOptionPane();
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = chooser.getSelectedFile();
        } else {

        }
        project2 = selectedFile.getAbsolutePath();
        try {
            String filename = selectedFile.getName();
            String extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
            String txt = "txt";
            String previousProject2 = "";

            while ((project1.compareTo(project2) == 0) || ((extension.compareTo(txt)) != 0)) {
                if (project1.compareTo(project2) == 0) {
                    optionPane.showMessageDialog(null, "Choose a different file than project1!");
                    chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    returnValue = chooser.showOpenDialog(this);
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        selectedFile = chooser.getSelectedFile();
                    } else {

                    }

                    filename = selectedFile.getName();
                    extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
                    if (((extension.compareTo(txt)) == 0) && (project1.compareTo(project2) == 0)) {
                        project2 = selectedFile.getAbsolutePath();
                    }
                }
                if ((extension.compareTo(txt)) != 0) {
                    optionPane.showMessageDialog(null, "Choose a txt file!");
                    chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    returnValue = chooser.showOpenDialog(this);
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        selectedFile = chooser.getSelectedFile();
                    } else {

                    }
                    filename = selectedFile.getName();
                    extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
                    if ((extension.compareTo(txt)) == 0) {
                        project2 = selectedFile.getAbsolutePath();
                    }
                    //AddButton1.setEnabled(true);!!!!!!!!!!!!!!!!!!!!!!!!
                }
            }

            //if (((extension.compareTo(txt)) == 0) && (compare12 == true)) {
            jButton2.setEnabled(false);
            jButton3.setEnabled(true);

        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int returnValue = chooser.showOpenDialog(this);
        File selectedFile = null;
        JOptionPane optionPane = new JOptionPane();
        JOptionPane exist = new JOptionPane();
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = chooser.getSelectedFile();
        } else {

        }
        project3 = selectedFile.getAbsolutePath();
        try {
            String filename = selectedFile.getName();
            String extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
            String txt = "txt";
            String previousProject3 = "";

            while ((project2.compareTo(project3) == 0) || (project1.compareTo(project3) == 0) || ((extension.compareTo(txt)) != 0)) {
                if (project1.compareTo(project3) == 0) {
                    optionPane.showMessageDialog(null, "Choose a different file than project1!");
                    chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    returnValue = chooser.showOpenDialog(this);
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        selectedFile = chooser.getSelectedFile();
                    } else {

                    }

                    filename = selectedFile.getName();
                    extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
                    if (((extension.compareTo(txt)) == 0) && (project1.compareTo(project3) == 0)) {
                        project3 = selectedFile.getAbsolutePath();
                    }
                }
                if (project2.compareTo(project3) == 0) {
                    optionPane.showMessageDialog(null, "Choose a different file than project2!");
                    chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    returnValue = chooser.showOpenDialog(this);
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        selectedFile = chooser.getSelectedFile();
                    } else {

                    }

                    filename = selectedFile.getName();
                    extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
                    if (((extension.compareTo(txt)) == 0) && (project3.compareTo(project2) == 0)) {
                        project3 = selectedFile.getAbsolutePath();
                    }
                }
                if ((extension.compareTo(txt)) != 0) {
                    optionPane.showMessageDialog(null, "Choose a txt file!");
                    chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    returnValue = chooser.showOpenDialog(this);
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        selectedFile = chooser.getSelectedFile();
                    } else {

                    }
                    filename = selectedFile.getName();
                    extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
                    if ((extension.compareTo(txt)) == 0) {
                        project3 = selectedFile.getAbsolutePath();
                    }
                    //AddButton1.setEnabled(true);!!!!!!!!!!!!!!!!!!!!!!!!
                }
            }

            //if (((extension.compareTo(txt)) == 0) && (compare12 == true)) {
            jButton3.setEnabled(false);

        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void readProject1Txt() throws IOException {
        File file = new File(project1);

        String line = null;
        int numOfLines = 0;
        int NoIndex = -1;
        int PartNameIndex = -1;
        boolean indexesFound = true;
        ArrayList<String> Nos = new ArrayList<>();
        ArrayList<String> PartNumbers = new ArrayList<>();

        Scanner scanner = new Scanner(file);
        while (scanner.hasNextLine()) {
            line = scanner.nextLine();
            System.out.println("next line "+ line);
            //scanner.nextLine();
            String[] space = line.split("\\s+");
            for(int i = 0; i<space.length; i++){
            System.out.println("splitedLine" + space[i]);
            }
            numOfLines++;
            System.out.println("line" + line.toString());
            while (indexesFound == false) {
                for (int i = 0; i < space.length; i++) {
                    System.out.println("splitedLine[i]" + space[i]);
                    if (space[i].equalsIgnoreCase("No.")) {
                        NoIndex = i;
                        indexesFound = true;
                        System.out.println("NoIndex" + NoIndex);
                    } else {
                        indexesFound = false;
                    }
                }
                for (int i = 0; i < space.length; i++) {
                    if (space[i].equalsIgnoreCase("PART.NAME")) {
                        PartNameIndex = i;
                        indexesFound = true;
                        System.out.println("PartNameIndex" + PartNameIndex);
                    } else {
                        indexesFound = false;
                    }
                }

            }
            System.out.println("NoIndex " + NoIndex + " PartNameIndex " + PartNameIndex);
            System.out.println("Nos" + Nos.toString());
            System.out.println("PartNumbers" + PartNumbers.toString());
        }

    }

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

    }//GEN-LAST:event_jButton2KeyPressed

    String project1;
    String project2;
    String project3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable F11to15T411;
    private javax.swing.JTable F11to15T482;
    private javax.swing.JTable F16to20T411;
    private javax.swing.JTable F16to20T482;
    private javax.swing.JTable F1to5T411;
    private javax.swing.JTable F1to5T482;
    private javax.swing.JTable F21to25T411;
    private javax.swing.JTable F21to25T482;
    private javax.swing.JTable F26to30T411;
    private javax.swing.JTable F26to30T482;
    private javax.swing.JTable F31to35T411;
    private javax.swing.JTable F31to35T482;
    private javax.swing.JTable F36to40T411;
    private javax.swing.JTable F36to40T482;
    private javax.swing.JTable F41to45T411;
    private javax.swing.JTable F41to45T482;
    private javax.swing.JTable F46to50T411;
    private javax.swing.JTable F46to50T482;
    private javax.swing.JTable F51T411;
    private javax.swing.JTable F51to55T482;
    private javax.swing.JTable F52T411;
    private javax.swing.JTable F53T411;
    private javax.swing.JTable F54T411;
    private javax.swing.JTable F55T411;
    private javax.swing.JTable F56T411;
    private javax.swing.JTable F56to60T482;
    private javax.swing.JTable F57T411;
    private javax.swing.JTable F58T411;
    private javax.swing.JTable F59T411;
    private javax.swing.JTable F60T411;
    private javax.swing.JTable F6to10T411;
    private javax.swing.JTable F6to10T482;
    private javax.swing.JTable OveflowFeederName;
    private javax.swing.JTable OverflowPosition;
    private javax.swing.JTable OverflowProjectName;
    private javax.swing.JTable R11to15T411;
    private javax.swing.JTable R11to15T482;
    private javax.swing.JTable R16to20T411;
    private javax.swing.JTable R16to20T482;
    private javax.swing.JTable R1to5T411;
    private javax.swing.JTable R1to5T482;
    private javax.swing.JTable R21to25T411;
    private javax.swing.JTable R21to25T482;
    private javax.swing.JTable R26to30T411;
    private javax.swing.JTable R26to30T482;
    private javax.swing.JTable R31to35T411;
    private javax.swing.JTable R31to35T482;
    private javax.swing.JTable R36to40T411;
    private javax.swing.JTable R36to40T482;
    private javax.swing.JTable R41to45T411;
    private javax.swing.JTable R46to50T411;
    private javax.swing.JTable R51T411;
    private javax.swing.JTable R52T411;
    private javax.swing.JTable R53T411;
    private javax.swing.JTable R54T411;
    private javax.swing.JTable R55T411;
    private javax.swing.JTable R56T411;
    private javax.swing.JTable R57T411;
    private javax.swing.JTable R58T411;
    private javax.swing.JTable R59T411;
    private javax.swing.JTable R60T411;
    private javax.swing.JTable R6to10T411;
    private javax.swing.JTable R6to10T482;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane61;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JScrollPane jScrollPane63;
    private javax.swing.JScrollPane jScrollPane64;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable45;
    // End of variables declaration//GEN-END:variables
}
